// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import template "html/template"

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

// Load provides a mock function with given fields: name
func (_m *Loader) Load(name string) (*template.Template, error) {
	ret := _m.Called(name)

	var r0 *template.Template
	if rf, ok := ret.Get(0).(func(string) *template.Template); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*template.Template)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
