package leaf

import (
	"fmt"
)

// assetFunc is the function declared by go-bindata.
type assetFunc func(string) ([]byte, error)

// BindataLoader is a wrapper around an Asset function generated by github.com/jteeuwen/go-bindata.
type BindataLoader struct {
	asset assetFunc
}

func NewBindataLoader(asset assetFunc) *BindataLoader {
	return &BindataLoader{
		asset: asset,
	}
}

func (l *BindataLoader) Load(name string) ([]byte, error) {
	template, err := l.asset(name)
	if err != nil {
		if err.Error() == fmt.Sprintf("Asset %s not found", name) {
			return nil, ErrTemplateNotFound
		}

		return nil, err
	}

	return template, nil
}
