package leaf

import "html/template"

// assetFunc is the function declared by go-bindata.
type assetFunc func(string) ([]byte, error)

// BindataLoader is a wrapper around an Asset function generated by github.com/jteeuwen/go-bindata.
type BindataLoader struct {
	asset assetFunc
}

func NewBindataLoader(asset assetFunc) *BindataLoader {
	return &BindataLoader{
		asset: asset,
	}
}

func (l *BindataLoader) Load(name string) (*template.Template, error) {
	asset, err := l.asset(name)
	if err != nil {
		return nil, err
	}

	return template.New("").Parse(string(asset))
}
